#!/bin/bash
################################################################################
# Common RTSM functions / setup / config
################################################################################

################################################################################
# FlexLM Tunnel Stuff
################################################################################
export ARMLMD_LICENSE_FILE="8224@127.0.0.1"

function setup_flexlm_tunnel
{
	# TODO - username needs to be generic
	#        perhaps the shh config can take care of it?
	gnome-terminal --geometry=32x4 --title "flexlm tunnel" -e "ssh -L 8224:localhost:8224 -L 18224:localhost:18224 -N ryan.harkin@flexlm.linaro.org -v"
}

TITLE_select_model="Select RTSM model"
PRE_ACTION_select_model="rtsm_show_config"
POST_ACTION_select_model="break"
select_model=( 
	"rtsm_select_model a15x1"
	"rtsm_select_model a15x2"
	"rtsm_select_model a15x4"
	"rtsm_select_model a15x1-a7x1"
	"rtsm_select_model a15x4-a7x4"
	separator
	"rtsm_select_model a9x4"
	separator
	"rtsm_select_model foundation"
	"rtsm_select_model aemv8"
	"rtsm_select_model aemv8_ve"
	"rtsm_select_model aemv8_ve_r0p3-46rel05"
	"rtsm_select_model aemv8_ve_r0p4-47rel02"
	"rtsm_select_model aemv8_ve_r0p4-50rel13"
	separator
	"rtsm_select_model fvp_base_aemv8a_r0p4-50rel13"
	separator
	"# old models"
	separator
	"rtsm_select_model v7.1_a15x1"
	"rtsm_select_model v7.1_a15x2"
	"rtsm_select_model v7.1_a15x4"
	"rtsm_select_model v7.1_a15x1-a7x1"
	"rtsm_select_model v7.1_a15x4-a7x4"
	separator
	"rtsm_select_model v8.0_a15x1"
	"rtsm_select_model v8.0_a15x2"
	"rtsm_select_model v8.0_a15x4"
	"rtsm_select_model v8.0_a15x1-a7x1"
	"rtsm_select_model v8.0_a15x4-a7x4"
)

################################################################################
# Select Model
################################################################################
function rtsm_select_model {
	if [ "$1" == "" ]; then
		submenu select_model
	else
		case $1 in
			"A9x4" | "a9x4" )
				echo "Selecting the A9x4 model"
				RTSM_MODEL_TYPE="8.2"
				RTSM_MODEL="/usr/local/DS-5/bin/FVP_VE_Cortex-A9x4"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a9.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a9x4
				fi
				;;
			"v7.1_A15x1" | "v7.1_a15x1" )
				echo "Selecting the A15x1 model (v7.1)"
				RTSM_MODEL_TYPE="7.1"
				RTSM_MODEL="/linaro/fastmodels/RTSM_7_1/Linux64_RTSM_VE_Cortex-A15x1/RTSM_VE_Cortex-A15x1"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x1.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15x1
				fi
				;;
			"v7.1_A15x2" | "v7.1_a15x2" )
				echo "Selecting the A15x2 model (v7.1)"
				RTSM_MODEL_TYPE="7.1"
				RTSM_MODEL="/linaro/fastmodels/RTSM_7_1/Linux64_RTSM_VE_Cortex-A15x2/RTSM_VE_Cortex-A15x2"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x2.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"v7.1_A15x4" | "v7.1_a15x4" )
				echo "Selecting the A15x4 model (v7.1)"
				RTSM_MODEL_TYPE="7.1"
				RTSM_MODEL="/linaro/fastmodels/RTSM_7_1/Linux64_RTSM_VE_Cortex-A15x4/RTSM_VE_Cortex-A15x4"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x4.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"v7.1_A15x1-A7x1" | "v7.1_A15x1-A7x1" )
				echo "Selecting the big.LITTLE model (v7.1)"
				RTSM_MODEL_TYPE="7.1"
				RTSM_MODEL=/linaro/fastmodels/RTSM_7_1/Linux64_RTSM_VE_Cortex-A15x1-A7x1/RTSM_VE_Cortex-A15x1-A7x1
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"v7.1_A15x4-A7x4" | "v7.1_A15x4-A7x4" )
				echo "Selecting the big.LITTLE model (v7.1)"
				RTSM_MODEL_TYPE="7.1"
				RTSM_MODEL=/linaro/fastmodels/RTSM_7_1/Linux64_RTSM_VE_Cortex-A15x4-A7x4/RTSM_VE_Cortex-A15x4-A7x4
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"v8.0_A15x1" | "v8.0_a15x1" )
				echo "Selecting the A15x1 model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/RTSM_8_0_1/models/Linux64_GCC-4.1/RTSM_VE_Cortex-A15x1"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x1.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15x1
				fi
				;;
			"v8.0_A15x2" | "v8.0_a15x2" )
				echo "Selecting the A15x2 model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/RTSM_8_0_1/models/Linux64_GCC-4.1/RTSM_VE_Cortex-A15x2"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x2.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"v8.0_A15x4" | "v8.0_a15x4" )
				echo "Selecting the A15x4 model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/RTSM_8_0_1/models/Linux64_GCC-4.1/RTSM_VE_Cortex-A15x4"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x4.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"v8.0_A15x1-A7x1" | "v8.0_a15x1-a7x1" )
				echo "Selecting the big.LITTLE model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/RTSM_8_0_1/models/Linux64_GCC-4.1/RTSM_VE_Cortex-A15x1-A7x1"
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"v8.0_A15x4-A7x4" | "v8.0_a15x4-a7x4" )
				echo "Selecting the big.LITTLE model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/RTSM_8_0_1/models/Linux64_GCC-4.1/RTSM_VE_Cortex-A15x4-A7x4"
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"A15x1" | "a15x1" )
				echo "Selecting the A15x1 model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/FVP_VE_Cortex-A15-A7_0.8.3.1900/models/Linux64_GCC-4.1/FVP_VE_Cortex-A15x1"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x1.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15x1
				fi
				;;
			"A15x2" | "a15x2" )
				echo "Selecting the A15x2 model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/FVP_VE_Cortex-A15-A7_0.8.3.1900/models/Linux64_GCC-4.1/FVP_VE_Cortex-A15x2"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x2.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"A15x4" | "a15x4" )
				echo "Selecting the A15x4 model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/FVP_VE_Cortex-A15-A7_0.8.3.1900/models/Linux64_GCC-4.1/FVP_VE_Cortex-A15x4"
				RTSM_UEFI_VARS=$HOME/uefi-vars-a15x4.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"A15x1-A7x1" | "a15x1-a7x1" )
				echo "Selecting the big.LITTLE model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/FVP_VE_Cortex-A15-A7_0.8.3.1900/models/Linux64_GCC-4.1/FVP_VE_Cortex-A15x1-A7x1"
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"A15x4-A7x4" | "a15x4-a7x4" )
				echo "Selecting the big.LITTLE model (v8.0.1)"
				RTSM_MODEL_TYPE="8.0.1"
				RTSM_MODEL="/linaro/fastmodels/FVP_VE_Cortex-A15-A7_0.8.3.1900/models/Linux64_GCC-4.1/FVP_VE_Cortex-A15x4-A7x4"
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_a15mpcore
				fi
				;;
			"Foundation" | "foundation" | "Foundation_v8" | "foundation_v8" )
				echo "Selecting the Foundation v8 model"
				RTSM_MODEL_TYPE="foundation"
				RTSM_MODEL="/linaro/fastmodels/Foundation_v8pkg/Foundation_v8"		
				RTSM_UEFI_VARS=$HOME/uefi-vars-foundation.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_foundation
				fi
				;;
			"AEMv8" | "aemv8" )
				basedir=/linaro/fastmodels/RTSM_AEMv8
				RTSM_MODEL_TYPE="AARCH64_VE"
				RTSM_MODEL="$basedir/ModelDebugger_7.1/bin/model_shell64 $basedir/lib/Linux64/RTSM_VE_AEMv8A.so "
				RTSM_UEFI_VARS=$HOME/uefi-vars-aarch64.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_aarch64
				fi
				;;
			"AEMv8_VE"  | "aemv8_ve")
				basedir=/linaro/fastmodels/RTSM_AEMv8_VE
				RTSM_MODEL_TYPE="AARCH64_VE"
				RTSM_MODEL="$basedir/bin/model_shell64 $basedir/models/Linux64_GCC-4.1/RTSM_VE_AEMv8A.so "
				RTSM_UEFI_VARS=$HOME/uefi-vars-aarch64.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_aarch64
				fi
				;;
			"AEMv8_VE_r0p3-46rel05" | "aemv8_ve_r0p3-46rel05" )
				basedir=/linaro/fastmodels/RTSM_AEMv8_VE_r0p3-46rel05
				RTSM_MODEL_TYPE="AARCH64_VE"
				RTSM_MODEL="$basedir/bin/model_shell64 $basedir/models/Linux64_GCC-4.1/RTSM_VE_AEMv8A.so "
				RTSM_UEFI_VARS=$HOME/uefi-vars-aarch64.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_aarch64
				fi
				;;
			"AEMv8_VE_r0p4-47rel02" | "aemv8_ve_r0p4-47rel02" )
				basedir=/linaro/fastmodels/RTSM_AEMv8_VE_r0p4-47rel02
				RTSM_MODEL_TYPE="AARCH64_VE"
				RTSM_MODEL="$basedir/bin/model_shell64 $basedir/models/Linux64_GCC-4.1/RTSM_VE_AEMv8A.so "
				RTSM_UEFI_VARS=$HOME/uefi-vars-aarch64.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_aarch64
				fi
				;;
			"AEMv8_VE_r0p4-50rel13" | "aemv8_ve_r0p4-50rel13" )
				basedir=/linaro/fastmodels/FVP_AEMv8_VE_r0p4-50rel13
				RTSM_MODEL_TYPE="AARCH64_VE"
				RTSM_MODEL="$basedir/bin/model_shell64 $basedir/models/Linux64_GCC-4.1/FVP_VE_AEMv8A.so "
				RTSM_UEFI_VARS=$HOME/uefi-vars-aarch64.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_aarch64
				fi
				;;
			"fvp_base_aemv8a_r0p4-50rel13" )
				basedir=/linaro/fastmodels/FVP_Base_AEMv8A-AEMv8A
				RTSM_MODEL_TYPE="FVP"
				#RTSM_MODEL="$basedir/bin/modeldebugger --verbose -y -n $basedir/models/Linux64_GCC-4.1/FVP_Base_AEMv8A-AEMv8A"
				RTSM_MODEL="$basedir/models/Linux64_GCC-4.1/FVP_Base_AEMv8A-AEMv8A"
				RTSM_UEFI_VARS=$HOME/uefi-vars-aarch64.fd
				if [ "$RTSM_UEFI" == "" ]; then
					rtsm_set_uefi_image rtsm_aarch64
				fi
				;;
		esac
		RTSM_MODEL_NAME=$1
	fi
}


################################################################################
# Set method boot the model
################################################################################
TITLE_select_boot_method="Select boot method"
PRE_ACTION_select_boot_method="rtsm_show_config"
POST_ACTION_select_boot_method="break"
select_boot_method=( 
	"rtsm_set_boot_method UEFI"
	"rtsm_set_boot_method AXFv7"
	"rtsm_set_boot_method AXFv8"
)

################################################################################
# Configure which UEFI image we will boot on the model
################################################################################
function rtsm_set_boot_method {
	if [ "$1" == "" ]; then
		submenu select_boot_method
	else
		case $1 in
			"UEFI")
				RTSM_BOOT_METHOD="UEFI"
				;;
			"AXFv7")
				RTSM_BOOT_METHOD="AXFv7"
				;;
			"AXFv8")
				RTSM_BOOT_METHOD="AXFv8"
				;;

			* )
				echo "ERROR: boot method $1 is not valid"
				;;
		esac
	fi
}


################################################################################
# Set binary AXF image used to boot the model
################################################################################
TITLE_select_axf="Select AXF binary to boot"
PRE_ACTION_select_axf="rtsm_show_config"
POST_ACTION_select_axf="break"
select_axf=( 
	"rtsm_set_axf_image android"
	"rtsm_set_axf_image ubuntu"
	"rtsm_set_axf_image alip"
	"rtsm_set_axf_image openembedded"

	separator

	"rtsm_set_axf_image /linaro/releases/oe/latest/img-foundation.axf"
	"rtsm_set_axf_image /linaro/releases/oe/latest/img.axf"

	separator

	"rtsm_set_axf_image /linaro/g.l.o/arm/uefi/uefi-next.git/ArmPlatformPkg/ArmVExpressPkg/Scripts/uefi-aarch64-bootstrap/uefi-bootstrap-el3-foundation.axf"
)

################################################################################
# Configure which UEFI image we will boot on the model
################################################################################
function rtsm_set_axf_image {
	if [ "$1" == "" ]; then
		submenu select_axf
	else
		case $1 in
			"android")
				rtsm_set_axf_image /linaro/snapshots/android/latest/boot/rtsm/linux-system-semi.axf
				;;
			"ubuntu")
				rtsm_set_axf_image /linaro/snapshots/ubuntu/latest/boot/rtsm/linux-system-semi.axf
				;;
			"alip")
				rtsm_set_axf_image /linaro/snapshots/alip/latest/boot/rtsm/linux-system-semi.axf
				;;
			"openembedded" | "oe")
				rtsm_set_axf_image /linaro/snapshots/oe/latest/img-foundation.axf
				;;
			"juice")
				rtsm_set_axf_image /linaro/snapshots/juice/latest/boot/linux-system-semi.axf
				;;

			* )
				if [ -f "$1" ]; then
					RTSM_AXF=$1
				else
					echo "ERROR: AXF image $1 does not exist"
					return
				fi
				;;
		esac
		RTSM_AXF_NAME=$1
		RTSM_BOOT_METHOD="AXFv8"
	fi
}




################################################################################
# Set binary image used to boot the model
################################################################################
TITLE_select_uefi="Select UEFI binary to boot"
PRE_ACTION_select_uefi="rtsm_show_config"
POST_ACTION_select_uefi="break"
select_uefi=( 
	"rtsm_set_uefi_image rtsm_a9x4"
	"rtsm_set_uefi_image rtsm_a15x1"
	"rtsm_set_uefi_image rtsm_a15mpcore"
	"rtsm_set_uefi_image rtsm_aarch64"
	separator
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-A9x4/RELEASE_ARMLINUXGCC/FV/RTSM_VE_CORTEX-A9_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-A15/RELEASE_ARMLINUXGCC/FV/RTSM_VE_CORTEX-A15_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-A15_MPCore/RELEASE_ARMLINUXGCC/FV/RTSM_VE_CORTEX-A15_MPCORE_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-AEMv8Ax4/RELEASE_ARMLINUXGCC/FV/RTSM_VE_AEMV8_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-FVP-AArch64/RELEASE_ARMLINUXGCC/FV/FVP_AARCH64_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-AEMv8Ax4-foundation/RELEASE_ARMLINUXGCC/FV/RTSM_VE_FOUNDATIONV8_EFI.fd"
	separator
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-A9x4/DEBUG_ARMLINUXGCC/FV/RTSM_VE_CORTEX-A9_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-A15/DEBUG_ARMLINUXGCC/FV/RTSM_VE_CORTEX-A15_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-A15_MPCore/DEBUG_ARMLINUXGCC/FV/RTSM_VE_CORTEX-A15_MPCORE_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-AEMv8Ax4/DEBUG_ARMLINUXGCC/FV/RTSM_VE_AEMV8_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-FVP-AArch64/DEBUG_ARMLINUXGCC/FV/FVP_AARCH64_EFI.fd"
	"rtsm_set_uefi_image /linaro/g.l.o/arm/uefi/uefi-next.git/Build/ArmVExpress-RTSM-AEMv8Ax4-foundation/DEBUG_ARMLINUXGCC/FV/RTSM_VE_FOUNDATIONV8_EFI.fd"
	separator
	"rtsm_set_uefi_image /linaro/releases/uefi/latest/uefi_rtsm_ve-ca9x4.bin"
	"rtsm_set_uefi_image /linaro/releases/uefi/latest/uefi_rtsm_ve-ca15.bin"
	"rtsm_set_uefi_image /linaro/releases/uefi/latest/uefi_rtsm_ve-aemv8.bin"
	"rtsm_set_uefi_image /linaro/releases/uefi/latest/uefi_fvp-base.bin"
	separator
	"rtsm_set_uefi_image /linaro/snapshots/uefi/latest/uefi_rtsm_ve-ca9x4.bin"
	"rtsm_set_uefi_image /linaro/snapshots/uefi/latest/uefi_rtsm_ve-ca15.bin"
	"rtsm_set_uefi_image /linaro/snapshots/uefi/latest/uefi_rtsm_ve-aemv8.bin"
	"rtsm_set_uefi_image /linaro/snapshots/uefi/latest/uefi_fvp-base.bin"
	separator
	"rtsm_set_uefi_image /linaro/snapshots/uefi-next/latest/uefi_rtsm_ve-ca9x4.bin"
	"rtsm_set_uefi_image /linaro/snapshots/uefi-next/latest/uefi_rtsm_ve-ca15.bin"
	"rtsm_set_uefi_image /linaro/snapshots/uefi-next/latest/uefi_rtsm_ve-aemv8.bin"
	"rtsm_set_uefi_image /linaro/snapshots/uefi-next/latest/uefi_fvp-base.bin"
	separator
	"rtsm_set_uefi_image /linaro/snapshots/uefi-lce-2013/latest/uefi_rtsm_ve-ca9x4.bin"
	"rtsm_set_uefi_image /linaro/snapshots/uefi-lce-2013/latest/uefi_rtsm_ve-ca15.bin"
	separator
	"rtsm_set_uefi_image /linaro/snapshots/android/latest/boot/rtsm/uefi_rtsm_ve-ca9x4.bin"
	"rtsm_set_uefi_image /linaro/snapshots/android/latest/boot/rtsm/uefi_rtsm_ve-ca15.bin"
	"rtsm_set_uefi_image /linaro/snapshots/ubuntu/latest/boot/rtsm/uefi_rtsm_ve-ca9x4.bin"
	"rtsm_set_uefi_image /linaro/snapshots/ubuntu/latest/boot/rtsm/uefi_rtsm_ve-ca15.bin"
	"rtsm_set_uefi_image /linaro/snapshots/alip/latest/boot/rtsm/uefi_rtsm_ve-ca9x4.bin"
	"rtsm_set_uefi_image /linaro/snapshots/alip/latest/boot/rtsm/uefi_rtsm_ve-ca15.bin"
	separator
	"rtsm_set_uefi_image /linaro/uefi/aarch64/aarch64-uefi-2013-02/RTSM_VE_AEMV8_EFI.fd"
	"rtsm_set_uefi_image /linaro/uefi/aarch64/aarch64-uefi-2013-05/RTSM_VE_AEMV8_EFI.fd"
)

################################################################################
# Configure which UEFI image we will boot on the model
################################################################################
function rtsm_set_uefi_image {
	if [ "$1" == "" ]; then
		submenu select_uefi
	else
		case $1 in
			"rtsm_a9x4" )
				RTSM_UEFI=/linaro/snapshots/uefi-next/latest/uefi_rtsm_ve-ca9x4.bin
				;;
			"rtsm_a15x1" )
				RTSM_UEFI=/linaro/snapshots/uefi-next/latest/uefi_rtsm_ve-ca15.bin
				;;
			"rtsm_a15mpcore" )
				RTSM_UEFI=/linaro/snapshots/uefi-next/latest/uefi_rtsm_ve-ca15.bin
				;;
			"rtsm_aarch64" )
				RTSM_UEFI=/linaro/snapshots/uefi-next/aarch64/uefi_rtsm_aarch64.bin
				;;
			"rtsm_foundation" )
				RTSM_AXF=/linaro/snapshots/uefi-next/aarch64/uefi-bootstrap-el3-foundation.axf
				RTSM_UEFI=/linaro/snapshots/uefi-next/aarch64/uefi_rtsm_foundation.bin
				;;
			* )
				RTSM_UEFI=$1
			;;
		esac
		RTSM_UEFI_NAME=$1
		RTSM_BOOT_METHOD=UEFI
	fi
}




################################################################################
TITLE_build_uefi="Build UEFI binary"
PRE_ACTION_build_uefi="rtsm_show_config"
POST_ACTION_build_uefi="break"
build_uefi=( 
	"rtsm_build_uefi rtsm_a9x4"
	"rtsm_build_uefi rtsm_a15x1"
	"rtsm_build_uefi rtsm_a15mpcore"
	"rtsm_build_uefi rtsm_aarch64"
)

################################################################################
function rtsm_build_uefi {
	if [ "$1" == "" ]; then
		if [ "$RTSM_UEFI_NAME" != "" ]; then
			rtsm_build_uefi $RTSM_UEFI_NAME
		else
			submenu build_uefi
		fi
	else
		cd $UEFI_WORKSPACE
		uefi-build.sh -b RELEASE $1
	fi
}

################################################################################
################################################################################
TITLE_select_mmc="Select MMC image"
PRE_ACTION_select_mmc="rtsm_show_config"
POST_ACTION_select_mmc="break"
select_mmc=( 
	'rtsm_set_mmc /linaro/releases/android-lsk/latest/vexpress*.img'
	'rtsm_set_mmc /linaro/releases/android/latest/vexpress*.img'
	'rtsm_set_mmc /linaro/releases/ubuntu/latest/vexpress*.img'
	'rtsm_set_mmc /linaro/releases/alip/latest/vexpress*.img'
	'rtsm_set_mmc /linaro/releases/oe-lsk/latest/vexpress*.img'
	'rtsm_set_mmc /linaro/releases/oe/latest/vexpress*.img'
	separator
	'rtsm_set_mmc /linaro/snapshots/android-lsk/latest/mmc.img'
	'rtsm_set_mmc /linaro/snapshots/android/latest/mmc.img'
	'rtsm_set_mmc /linaro/snapshots/ubuntu/latest/mmc.img'
	'rtsm_set_mmc /linaro/snapshots/alip/latest/mmc.img'
	'rtsm_set_mmc /linaro/snapshots/oe-lsk/latest/mmc.img'
	'rtsm_set_mmc /linaro/snapshots/oe/latest/mmc.img'
	separator
	'rtsm_set_mmc /linaro/aarch64/juice/juice-release-13.03.1/mmc.bin'
	'rtsm_set_mmc /linaro/aarch64/juice/juice-aosp-132/mmc.bin'
	'rtsm_set_mmc /linaro/aarch64/juice/juice-base-aosp-027/mmc.bin'
)
################################################################################
# Network enable/disable
################################################################################
function rtsm_set_mmc {
	if [ "$1" == "" ]; then
		submenu select_mmc
	else
		if [ ! -f $1 ]; then
			echo "MMC image $1 does not exist"
		else
			echo "Set MMC image to $1"
			RTSM_MMC=$1
		fi
	fi
}

################################################################################
# Network enable/disable
################################################################################
function rtsm_enable_networking
{
    NETWORK_ARGS="\
        -C motherboard.hostbridge.interfaceName=ARM$USER \
        -C motherboard.smsc_91c111.enabled=true \
        -C motherboard.smsc_91c111.mac_address=00:02:f7:ef:67:e6"

	rtsm_show_config
}

function rtsm_disable_networking
{
    NETWORK_ARGS=""
	rtsm_show_config
}


################################################################################
# Show the config we're currently using
################################################################################
function rtsm_show_config {
	echo "RTSM_MODEL_NAME    = $RTSM_MODEL_NAME"
	echo "RTSM_MODEL_TYPE    = $RTSM_MODEL_TYPE"
	echo "RTSM_MODEL         = $RTSM_MODEL"
	echo "RTSM_BOOT_METHOD   = $RTSM_BOOT_METHOD"
	echo "RTSM_UEFI_NAME     = $RTSM_UEFI_NAME"
	echo "RTSM_UEFI          = $RTSM_UEFI"
	echo "RTSM_AXF_NAME      = $RTSM_AXF_NAME"
	echo "RTSM_AXF           = $RTSM_AXF"
	echo "RTSM_MMC           = $RTSM_MMC"
	echo "RTSM_UEFI_VARS     = $RTSM_UEFI_VARS"
    echo "NETWORK_ARGS       = $NETWORK_ARGS"
}


################################################################################
# Run the model with the parameters specified in the environment vars
################################################################################
function rtsm_run
{
	# Now validate our parameters
	##if [ ! -f "$RTSM_MODEL" ]; then
	if [ "`which $RTSM_MODEL`" == "" ]; then
		echo "The model binary $RTSM_MODEL does not exist"
		return
	fi
	if [ "$RTSM_MMC" != "" ]; then
		if [ ! -f "$RTSM_MMC" ]; then
			echo "The MMC card image $RTSM_MMC does not exist"
			return
		fi
	else
		echo "***********************************************"
		echo "**** WARNING: running without an MMC image ****"
		echo "***********************************************"
	fi

	# TODO - check $RTSM_AXF also
	case $RTSM_BOOT_METHOD in
		"UEFI" | "uefi")
			if [ -f "$RTSM_UEFI" ]; then
				echo "Configuring RTSM to run with UEFI..."
				case $RTSM_MODEL_TYPE in
					"7.1" | "8.0.1" | "8.2" | "AARCH64_VE" )
						echo "Running VE model"
						cmd="$RTSM_MODEL \
							-C motherboard.flashloader0.fname=$RTSM_UEFI \
							-C motherboard.flashloader1.fname=$RTSM_UEFI_VARS \
							-C motherboard.flashloader1.fnameWrite=$RTSM_UEFI_VARS \
							-C motherboard.mmc.p_mmc_file=$RTSM_MMC \
							-C motherboard.pl011_uart0.unbuffered_output=true \
							$NETWORK_ARGS"
						;;
					"FVP" )
						echo "Running Base Model"
						cmd="$RTSM_MODEL \
							-C cluster0.register_reset_data=0x0 \
							-C cluster1.register_reset_data=0x0 \
							-C bp.refcounter.non_arch_start_at_default=1 \
							-C pctl.startup=0.0.*.* \
							-C cci400.force_on_from_start=1 \
							-C bp.secure_memory=0 \
							-C cluster0.NUM_CORES=2 \
							-C cluster1.NUM_CORES=2 \
							-C cache_state_modelled=0 \
							-C bp.pl011_uart0.untimed_fifos=1 \
							-C gicv3.gicv2-only=true \
							-C cluster0.gic.GICD-offset=0x1000 \
							-C cluster0.gic.GICC-offset=0x2000 \
							-C cluster0.gic.GICH-offset=0x4000 \
							-C cluster0.gic.GICH-other-CPU-offset=0x5000 \
							-C cluster0.gic.GICV-offset=0x6000 \
							-C cluster0.gic.PERIPH-size=0x8000 \
							-C cluster1.gic.GICD-offset=0x1000 \
							-C cluster1.gic.GICC-offset=0x2000 \
							-C cluster1.gic.GICH-offset=0x4000 \
							-C cluster1.gic.GICH-other-CPU-offset=0x5000 \
							-C cluster1.gic.GICV-offset=0x6000 \
							-C cluster1.gic.PERIPH-size=0x8000 \
							-C bp.flashloader0.fname=$RTSM_UEFI \
							-C bp.flashloader1.fname=$RTSM_UEFI_VARS \
							-C bp.flashloader1.fnameWrite=$RTSM_UEFI_VARS \
							-C bp.mmc.p_mmc_file=$RTSM_MMC"
						;;
					"foundation")
						echo "Running the foundation model"
						# TODO - this probably doesn't work - I think it needs an EL3 binary or something...
						$RTSM_MODEL \
							--image $RTSM_UEFI \
							--block-device $RTSM_MMC \
							--network=nat
						;;
					* )
						echo "unknown model version $model"
						;;
				esac
			else
				echo "ERROR: UEFI Binary does not exist: $RTSM_UEFI"
				return
			fi
			;;
		"AXFv7" | "axfv7")
# TODO - $RTSM_KERNEL
# TODO - $RTSM_DTB
# TODO - $RTSM_INITRD
# the kernel, dtb, initrd and boot wrapper are normally in the boot partition of the image being tested....
# perhaps use kpartx to extract them?
#			extra_args=-C cluster.cpu0.semihosting-cmd_line="--kernel $RTSM_KERNEL --dtb $RTSM_DTB --initrd $RTSM_INITRD -- $RTSM_CMDLINE"
			;;	
		"AXFv8" | "axfv8")
			if [ -f "$RTSM_AXF" ]; then
				case "$RTSM_MODEL_TYPE" in
					"foundation" | "Foundation")
						echo "Configuring Foundation RTSM to run an AXF using ARMv8 method..."
						cmd="$RTSM_MODEL \
							--image $RTSM_AXF \
							--block-device $RTSM_MMC \
							--network nat"
						;;
					"AARCH64_VE")
						echo "Configuring RTSM to run an AXF using ARMv8 method..."
						cmd="$RTSM_MODEL \
							-a $RTSM_AXF \
							-C motherboard.flashloader0.fname=$RTSM_UEFI \
							-C motherboard.flashloader1.fname=$RTSM_UEFI_VARS \
							-C motherboard.flashloader1.fnameWrite=$RTSM_UEFI_VARS \
							-C motherboard.mmc.p_mmc_file=$RTSM_MMC \
							-C motherboard.pl011_uart0.unbuffered_output=true \
							$NETWORK_ARGS"
						;;
				esac
			else
				echo "err"
				return
			fi
			;;
		*)
			echo "RTSM_BOOT_METHOD $RTSM_BOOT_METHOD is not valid"
			return
			;;
	esac

	if [ "$RTSM_QUIET" != "yes" ]; then
		rtsm_show_config
		echo "RTSM command       = $cmd"
	fi

	touch $RTSM_UEFI_VARS
	$cmd
}



################################################################################
# Load config
################################################################################
function rtsm_load_config {
	if [ "$1" == "" ]; then
		TITLE_load_config="Load Config"
		PRE_ACTION_load_config="rtsm_show_config"
		POST_ACTION_load_config="break"

		load_config=( 
			"rtsm_load_config 1 `grep TITLE $HOME/uefi-tools/menus/.1.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 2 `grep TITLE $HOME/uefi-tools/menus/.2.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 3 `grep TITLE $HOME/uefi-tools/menus/.3.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 4 `grep TITLE $HOME/uefi-tools/menus/.4.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 5 `grep TITLE $HOME/uefi-tools/menus/.5.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 6 `grep TITLE $HOME/uefi-tools/menus/.6.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 7 `grep TITLE $HOME/uefi-tools/menus/.7.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 8 `grep TITLE $HOME/uefi-tools/menus/.8.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 9 `grep TITLE $HOME/uefi-tools/menus/.9.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_load_config 0 `grep TITLE $HOME/uefi-tools/menus/.0.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
		)
		submenu load_config
	else
		config_file="$HOME/uefi-tools/menus/.$1.config"
		echo "Load config from $1"
		source $config_file
	fi
}


################################################################################
# Load config
################################################################################
function rtsm_save_config {
	if [ "$1" == "" ]; then
		TITLE_save_config="Save Config"
		PRE_ACTION_save_config="rtsm_show_config"
		POST_ACTION_save_config="break"
		save_config=( 
			"rtsm_save_config 0 `grep TITLE $HOME/uefi-tools/menus/.0.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 1 `grep TITLE $HOME/uefi-tools/menus/.1.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 2 `grep TITLE $HOME/uefi-tools/menus/.2.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 3 `grep TITLE $HOME/uefi-tools/menus/.3.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 4 `grep TITLE $HOME/uefi-tools/menus/.4.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 5 `grep TITLE $HOME/uefi-tools/menus/.5.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 6 `grep TITLE $HOME/uefi-tools/menus/.6.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 7 `grep TITLE $HOME/uefi-tools/menus/.7.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 8 `grep TITLE $HOME/uefi-tools/menus/.8.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
			"rtsm_save_config 9 `grep TITLE $HOME/uefi-tools/menus/.9.config  | sed 's/export RTSM_TITLE=//' 2> /dev/null`"
		)
		submenu save_config
	else
		config_file="$HOME/uefi-tools/menus/.$1.config"
		echo "Save config to $config_file"
		echo -n "Enter a description for this config: "
		read RTSM_TITLE
		echo "export RTSM_TITLE=\"$RTSM_TITLE\"" > $config_file
		echo "export RTSM_MODEL_NAME=\"$RTSM_MODEL_NAME\"" >> $config_file
		echo "export RTSM_MODEL_TYPE=\"$RTSM_MODEL_TYPE\"" >> $config_file
		echo "export RTSM_MODEL=\"$RTSM_MODEL\"" >> $config_file
		echo "export RTSM_BOOT_METHOD=\"$RTSM_BOOT_METHOD\"" >> $config_file
		echo "export RTSM_UEFI_NAME=\"$RTSM_UEFI_NAME\"" >> $config_file
		echo "export RTSM_UEFI=\"$RTSM_UEFI\"" >> $config_file
		echo "export RTSM_AXF_NAME=\"$RTSM_AXF_NAME\"" >> $config_file
		echo "export RTSM_AXF=\"$RTSM_AXF\"" >> $config_file
		echo "export RTSM_MMC=\"$RTSM_MMC\"" >> $config_file
		echo "export RTSM_UEFI_VARS=\"$RTSM_UEFI_VARS\"" >> $config_file
		echo "export NETWORK_ARGS=\"$NETWORK_ARGS\""  >> $config_file
	fi
}

