#!/bin/bash
################################################################################
# Month End
#
# At the end of the month, we:
#
# 1) Merge the current monthly branch to the release branch
# 2) Tag the release branch with linaro-uef-YYYY.MM
################################################################################


################################################################################
source "`dirname $0`"/uefi-common
################################################################################
cd $UEFI_NEXT_GIT

TAG=$(uefi_next_release_tag)

################################################################################
# Parse command line parameters
################################################################################
while [ "$1" != "" ]; do
    case $1 in
        -t | --tag )
            shift
			echo "Over-riding release tag to $1"
            TAG=$1
            ;;


        /h | /? | -? | -h | --help )
			echo "$0"
			echo "  optional parameters:"
			echo "    --tag <release tag>"
            exit
            ;;
        * )
            usage
			echo "unknown arg $1"
            exit 1
    esac
    shift
done
################################################################################

echo "--------------------------------------------------------------------------------"
echo "Updating linaro-release"
echo "--------------------------------------------------------------------------------"
force_update_branch $(uefi_next_current_month_branch) linaro-release
git tag $TAG

