#!/bin/bash
# simple example:
# kernel: uImage
# mmci.fmax: 4000000
# using device tree: n
#
# uefi-config > /dev/ttyUSB1
#
# more complex example:
# kernel binary: uImage.tc2
# mmci.fmax: 4000000
# Using device tree: y
# Device tree file: vexpress-v2p-ca15-tc2.dtb
#
# uefi-config uImage.tc2 4000000 y vexpress-v2p-ca15-tc2.dtb > /dev/ttyUSB3
#
# uefi-config uImage 4000000 y v2p-ca15-tc1.dtb ~/bin/uefi-base-config-commands-android  > /dev/ttyUSB2
##

UEFI_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


if [ $# -lt 1 ]
then
	uimage="uImage"
else
	uimage=$1
fi

if [ $# -lt 2 ]
then
	mmci="4000000"
else
	mmci=$2
fi

if [ $# -lt 3 ]
then
	fdt="n"
else
	fdt=$3
fi

if [ $# -lt 4 ]
then
	fdt_name="v2p-ca9.dtb"
else
	fdt_name=$4
fi

if [ $# -eq 5 ]
then
	file=$5
else
	file=$UEFI_PATH/uefi-base-config-commands
fi

#echo kernel uImage filename: $uimage
#echo mmci speed:             $mmci
#echo has fdt:                $fdt
#echo fdt name:               $fdt_name
#echo base config:            $file

sed s/KERNEL_UIMAGE/$uimage/ $file | sed s/MMCI_FREQ/$mmci/ | sed s/HAS_FDT/$fdt/ | slowuart

if [ "$fdt" = "y" ]
then
	sed s/FDT_NAME/$fdt_name/ $UEFI_PATH/uefi-base-config-commands-add-fdt | slowuart
fi
