#!/bin/bash
################################################################################
#
# uefi-setup
#
################################################################################

MY_PATH="`dirname \"$0\"`"              # relative
DEFAULT_CONFIG=$MY_PATH/uefi-tools.config
CONFIG_FILE=~/.uefi-tools.config

source $DEFAULT_CONFIG
if [ -f "$CONFIG_FILE" ]
then
	echo "Over-riding global config with $CONFIG_FILE"
	source $CONFIG_FILE
fi

function force_update_branch {
	src=`git branch --list $1 | sed "s/*//"`
	dest=`git branch --list $2 | sed "s/*//"`
	if [ "$src" != "" ]
	then
		if [ "$dest" != "" ]
		then
			echo "Force updating \"$dest\" from \"$src\""
			git checkout $src
			git reset --hard HEAD && git clean -dfx
			rm -rf $TMP_DIR
			mkdir -p $TMP_DIR
			cp -R * $TMP_DIR

			git checkout $dest
			git merge --no-commit -Xtheirs $src
			echo "########################################################################"
			echo "### Any above error messages about 'Automatic merge failed' are expected"
			echo "########################################################################"
			rm -rf *
			cp -R $TMP_DIR/* .
			git add -A
			git commit -s -m "Merging $src into $dest"
		fi
	fi
}
function uefi_next_current_month_branch {
	echo `git branch --list linaro-tracking-????.?? | tail -1 | sed "s/*//"`
}

function uefi_next_internal_current_month_branch {
	echo `git branch --list linaro-internal-tracking-????.?? | tail -1 | sed "s/*//"`
}

function uefi_next_next_month {
	YYYY=`date +%Y`
	MM=`date +%m`
    MM=$(expr $MM + 1)
	MM=$(printf "%.2d" "$MM")

	if [ "$MM" == "13" ]
    then
    	YYYY=$(expr $YYYY + 1)
		MM=01
    fi
	echo $YYYY.$MM
}

function uefi_next_get_YYYYMM {
	YYYY=`date +%Y`
	MM=`date +%m`
	echo $YYYY.$MM
}

function uefi_next_next_month_branch {
	echo linaro-tracking-$(uefi_next_next_month)
}

function uefi_next_internal_next_month_branch {
	echo linaro-internal-tracking-$(uefi_next_next_month)
}

function uefi_next_current_rc {
	version=`git tag --list linaro-uefi-????.??-rc* | tail -1`
	echo $version
}

function uefi_next_release_tag {
	tag=`git tag --list linaro-uefi-????.??-rc* | tail -1 | sed "s/-rc.*//"`
	echo $tag
}

function uefi_next_internal_current_rc {
	version=`git tag --list linaro-uefi-internal-????.??-rc* | tail -1`
	echo $version
}

function uefi_next_next_rc {
	version=`git tag --list linaro-uefi-$(uefi_next_get_YYYYMM)-rc* | tail -1`
	if [ "$version" == "" ]; then
		RC=1
	else
		[[ "$version" =~ (.*[^0-9])([0-9]+)$ ]] && version="${BASH_REMATCH[1]}$((${BASH_REMATCH[2]} + 1))";
		RC=`echo $version | sed 's#linaro-uefi-.*-rc##g'`
	fi
	echo linaro-uefi-$(uefi_next_get_YYYYMM)-rc$RC
}

function uefi_next_internal_next_rc {
	# TODO: this should return a tag matching the latest uefi-next -rc
	#       but currently, if we've just tagged uefi-next as, eg, -rc4
	#       this function will tag the internal tree as -rc5, even though
	#       the internal tree doesn't have an -rc4.
	version=`git tag --list linaro-uefi-$(uefi_next_get_YYYYMM)-rc* | tail -1`
	if [ "$version" == "" ]; then
		RC=1
	else
		[[ "$version" =~ (.*[^0-9])([0-9]+)$ ]] && version="${BASH_REMATCH[1]}$((${BASH_REMATCH[2]} + 1))";
		RC=`echo $version | sed 's#linaro-uefi-.*-rc##g'`
	fi
	echo linaro-uefi-internal-$(uefi_next_get_YYYYMM)-rc$RC
}

function uefi_next_list_topics {
	topics=(`git branch --list linaro-topic-* | sed "s/*//"`)

	for topic in "${topics[@]}" ; do
		echo "                          $topic"
	done
	}

function uefi_next_list_internal_topics {
	topics=(`git branch --list linaro-internal-topic-* | sed "s/*//"`)
	for topic in "${topics[@]}" ; do
		echo "                          $topic"
	done
}

RESULT_BUF=`echo -e --------------------------------------------`
PASS_COUNT=0
FAIL_COUNT=0

function log_result
{
	if [ $1 -eq 0 ]; then
		RESULT_BUF="`printf \"%s\n%32s\tpass\" \"$RESULT_BUF\" \"$2\"`"
		PASS_COUNT=$(($PASS_COUNT + 1))
	else
		RESULT_BUF="`printf \"%s\n%32s\tfail\" \"$RESULT_BUF\" \"$2\"`"
		FAIL_COUNT=$(($FAIL_COUNT + 1))
	fi
}

function print_result
{
	printf "%s" "$RESULT_BUF"
	echo -e "\n--------------------------------------------"
	printf "pass\t$PASS_COUNT\n"
	printf "fail\t$FAIL_COUNT\n"

	return $FAIL_COUNT
}

