#!/bin/bash
################################################################################
# Push all updates/tags/branches from uefi/uefi-next for release.
#
################################################################################

################################################################################
source "`dirname $0`"/uefi-common
################################################################################
cd "$UEFI_NEXT_GIT"
TAG=$(uefi_next_release_tag)

################################################################################
# Parse command line parameters
################################################################################
while [ "$1" != "" ]; do
    case $1 in
        -t | --tag )
            shift
			echo "Over-riding release tag to $1"
            TAG=$1
            ;;


        /h | /? | -? | -h | --help )
			echo "$0"
			echo "  optional parameters:"
			echo "    --tag <release tag>"
            exit
            ;;
        * )
            usage
			echo "unknown arg $1"
            exit 1
    esac
    shift
done
################################################################################

echo "Pushing linaro-release to $UEFI_NEXT_GIT_PUSH_REMOTE:"
git push "$UEFI_NEXT_GIT_PUSH_REMOTE" linaro-release

echo "Pushing $TAG to $UEFI_NEXT_GIT_PUSH_REMOTE:"
git push "$UEFI_NEXT_GIT_PUSH_REMOTE" $TAG

cd "$UEFI_GIT"
echo "Pushing $TAG to $UEFI_GIT_PUSH_REMOTE:"
git push $UEFI_GIT_PUSH_REMOTE $TAG

echo "Pushing master to $UEFI_GIT_PUSH_REMOTE:"
git push $UEFI_GIT_PUSH_REMOTE master
