#!/bin/bash
################################################################################
################################################################################
source "`dirname $0`"/uefi-common
################################################################################
# Defaults
################################################################################

################################################################################
function usage
{
	echo "Usage: $0"
	echo "  This command does not take any parameters"
}

while [ "$1" != "" ]; do
    case $1 in

        /h | /? | -? | -h | --help )
            usage
            exit
            ;;
        -* )
            usage
			echo "unknown arg $1"
            exit 1
    esac
    shift
done

cd $UEFI_NEXT_GIT

################################################################################
# 1) update the master branch

## update the branches on the local uefi-next.git to the local Tianocore clones
echo "--------------------------------------------------------------------------------"
echo "Updating master branch"
echo "--------------------------------------------------------------------------------"
echo "edk2"
cd $UEFI_NEXT_GIT
git checkout linaro-tracking
git remote update tianocore-edk2
git branch -f --track master tianocore-edk2/$UEFI_TIANOCORE_EDK2_MAIN_BRANCH

# 2) tag it
git checkout master
echo "--------------------------------------------------------------------------------"
TAG=linaro-base-$(uefi_next_get_YYYYMM)
echo "Tagging monthly base as $TAG"
git tag $TAG

exit
################################################################################
