#!/bin/bash

################################################################################
source "`dirname $0`"/uefi-common
################################################################################

cd $UEFI_NEXT_GIT
git reset --hard HEAD && git clean -dfx
git checkout linaro-release

RELEASE_TAG=$(uefi_next_release_tag)
echo "--------------------------------------------------------------------------------"
echo "Release tag is '$RELEASE_TAG'"
echo "--------------------------------------------------------------------------------"

echo "--------------------------------------------------------------------------------"
echo "Add uefi-next remote"
echo "--------------------------------------------------------------------------------"
# fetch the latest updates from uefi-next
cd $UEFI_GIT
git checkout master
git remote add uefi-next $UEFI_NEXT_GIT
echo "--------------------------------------------------------------------------------"
echo "Fetch latest content from uefi-next"
echo "--------------------------------------------------------------------------------"
git fetch --no-tags -f uefi-next

echo "--------------------------------------------------------------------------------"
echo "Merge uefi-next/linaro-release"
echo "--------------------------------------------------------------------------------"
force_update_branch uefi-next/linaro-release master

git tag $RELEASE_TAG

