#!/bin/bash
################################################################################
# restore all the main branches with versions starting with $PREFIX
# - topic branches
# - tracking branches, eg armlt-tracking and linaro-tracking
# - master
################################################################################
source "`dirname $0`"/uefi-common
################################################################################


################################################################################
function usage
{
	echo "Usage: $0 <prefix>"
}
################################################################################

if [ "$1" = "" ]
then
	PREFIX="previous"
	echo "Using default prefix: $PREFIX"
else
	PREFIX=$1
    echo "PREFIX is $PREFIX"
fi

shift
echo "num args = $#"
if [ $# -eq 0 ]
then
	branches=( 
		`git branch --list linaro-topic-* linaro-internal-feature-* linaro-internal-topic-* | sed "s/*//"`
		master
		armlt-tracking
		linaro-tracking
	)
else
	while [ "$1" != "" ]; do
		branches=(${branches[@]} "$1")
		shift
	done
fi

echo "prefix  = $PREFIX"
echo "branches = ${branches[@]}"

cd $UEFI_NEXT_GIT

current_branch=`git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`

for branch in "${branches[@]}" ; do
	echo "--------------------------------------------------------------------------------"
	echo "Restoring $PREFIX-$branch to $branch"

	# the only reason for checking out $PREFIX-branch is to make sure we aren't currently checking
	# out "$branch"
	git checkout $PREFIX-$branch
	git branch -D $branch
	git branch $branch $PREFIX-$branch

	if [ "$?" != "0" ]
	then
		echo "********************************************************************************"
		echo "Error during restore of $branch"
		echo "********************************************************************************"
		exit 1
	fi
done

git checkout $current_branch
