#!/bin/bash
################################################################################
#
# uefi-status
#
# Show the status of the uefi-next.git and uefi.git trees as held locally
#
################################################################################

################################################################################
source "`dirname $0`"/uefi-common
################################################################################
cd $UEFI_NEXT_GIT

echo "REPO            PUSH REMOTE     LOCATION"
echo "--------------  --------------- ------------------------------------"
printf "%-15s %-15s %-20s\n" "uefi.git" $UEFI_GIT_PUSH_REMOTE $UEFI_GIT
printf "%-15s %-15s %-20s\n" "" "" $UEFI_GIT_URL
printf "%-15s %-15s %-20s\n" "" "" $UEFI_GIT_PUSH_URL
printf "%-15s %-15s %-20s\n" "uefi-next.git" $UEFI_NEXT_GIT_PUSH_REMOTE $UEFI_NEXT_GIT
printf "%-15s %-15s %-20s\n" "" "" $UEFI_NEXT_URL
printf "%-15s %-15s %-20s\n" "" "" $UEFI_NEXT_PUSH_URL
printf "%-15s %-15s %-20s\n" "" $UEFI_INTERNAL_GIT_PUSH_REMOTE $UEFI_NEXT_GIT
printf "%-15s %-15s %-20s\n" "" "" $UEFI_INTERNAL_GIT_URL
printf "%-15s %-15s %-20s\n" "" "" $UEFI_INTERNAL_GIT_PUSH_URL
echo ""

echo "UPSTREAM                  LOCATION                                                     BRANCH"
echo "------------------------  ------------------------------------------------------------ ------"
printf "%-25s %-60s %-20s\n" $UEFI_TIANOCORE_EDK2_REMOTE $UEFI_TIANOCORE_EDK2_URL $UEFI_TIANOCORE_EDK2_MAIN_BRANCH

echo ""
echo "PUBLIC BRANCHES"
echo "------------------------------------------------------------------------"
echo "Current monthly branch    $(uefi_next_current_month_branch)"
echo "Next    monthly branch    $(uefi_next_next_month_branch)"
echo "Current RC                $(uefi_next_current_rc)"
echo "Next    RC                $(uefi_next_next_rc)"
echo "This month's release tag  $(uefi_next_release_tag)"
echo ""
echo "Topic branches"
echo "$(uefi_next_list_topics)"

echo ""
echo "INTERNAL BRANCHES"
echo "------------------------------------------------------------------------"
echo "Current monthly branch    $(uefi_next_internal_current_month_branch)"
echo "Next    monthly branch    $(uefi_next_internal_next_month_branch)"
echo "Current RC                $(uefi_next_internal_current_rc)"
echo "Next    RC                $(uefi_next_internal_next_rc)"
echo ""
echo "Internal topic branches"
echo "$(uefi_next_list_internal_topics)"
