#!/bin/bash
# simple example:
# kernel: uImage
# mmci.fmax: 4000000
# using device tree: n
#
# uefi-config > /dev/ttyUSB1
#
# more complex example:
# kernel binary: uImage.tc2
# mmci.fmax: 4000000
# Using device tree: y
# Device tree file: vexpress-v2p-ca15-tc2.dtb
#
# uefi-config uImage.tc2 4000000 y vexpress-v2p-ca15-tc2.dtb > /dev/ttyUSB3
#
# uefi-config uImage 4000000 y v2p-ca15-tc1.dtb android  > /dev/ttyUSB2
# uefi-config uImage 4000000 y v2p-ca15-tc1.dtb ubuntu  > /dev/ttyUSB2
##

UEFI_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

KERNEL_CMDLINE_UBUNTU="console=ttyAMA0,38400n8 root=/dev/mmcblk0p2 rootwait ro mem=1024M ip=dhcp clcd=xvga mmci.fmax=MMCI_FREQ"
KERNEL_CMDLINE_ANDROID="console=tty0 console=ttyAMA0,38400n8 rootwait ro init=/init androidboot.console=ttyAMA0 mmci.fmax=MMCI_FREQ"

if [ $# -lt 1 ]
then
	uimage="uImage"
else
	uimage=$1
fi

if [ $# -lt 2 ]
then
	mmci="4000000"
else
	mmci=$2
fi

if [ $# -lt 3 ]
then
	fdt="n"
else
	fdt=$3
fi

if [ $# -lt 4 ]
then
	fdt_name="v2p-ca9.dtb"
else
	fdt_name=$4
fi

if [ $# -lt 5 ]
then
	cmdline=$KERNEL_CMDLINE_UBUNTU
else
	cmdline=$KERNEL_CMDLINE_UBUNTU
	if [ "$5" = "ubuntu" ]
	then
		cmdline=$KERNEL_CMDLINE_UBUNTU
	else
		cmdline=$KERNEL_CMDLINE_ANDROID
	fi
fi

# It's important to run sed in the right order so that the constants are resolved fully
sed s/KERNEL_UIMAGE/$uimage/ $UEFI_PATH/uefi-base-config-commands | sed "s%KERNEL_CMDLINE%$cmdline%" | sed s/MMCI_FREQ/$mmci/ | sed s/HAS_FDT/$fdt/ | slowuart

if [ "$fdt" = "y" ]
then
	sed s/FDT_NAME/$fdt_name/ $UEFI_PATH/uefi-base-config-commands-add-fdt | slowuart
fi
